import type { Genre } from '../types/models';

export const GENRES: Record<Genre, string> = {
  'roman': 'Roman',
  'science-fiction': 'Science-fiction',
  'fantaisie': 'Fantaisie',
  'thriller': 'Thriller',
  'romance': 'Romance',
  'historique': 'Historique',
  'policier': 'Policier',
  'horreur': 'Horreur',
  'jeunesse': 'Jeunesse',
  'poesie': 'Poésie',
  'nouvelle': 'Nouvelle',
  'autre': 'Autre',
};

export const UI = {
  appName: 'Plume',
  tagline: 'Votre atelier d\'écriture',

  newProject: 'Nouveau projet',
  editProject: 'Modifier le projet',
  deleteProject: 'Supprimer le projet',
  deleteConfirm: 'Êtes-vous sûr de vouloir supprimer ce projet ? Cette action est irréversible.',
  noProjects: 'Aucun projet pour le moment',
  noProjectsHint: 'Créez votre premier projet pour commencer à écrire.',

  projectTitle: 'Titre',
  projectTitlePlaceholder: 'Le titre de votre roman...',
  projectSummary: 'Résumé',
  projectSummaryPlaceholder: 'Un court résumé de votre histoire...',
  projectGenre: 'Genre',

  newChapter: 'Nouveau chapitre',
  newScene: 'Nouvelle scène',
  chapterDefault: 'Chapitre sans titre',
  sceneDefault: 'Scène sans titre',
  deleteChapter: 'Supprimer le chapitre',
  deleteScene: 'Supprimer la scène',
  deleteChapterConfirm: 'Supprimer ce chapitre et toutes ses scènes ?',
  deleteSceneConfirm: 'Supprimer cette scène ?',

  editorPlaceholder: 'Commencez à écrire...',
  emptyStateTitle: 'Aucune scène sélectionnée',
  emptyStateDescription: 'Sélectionnez ou créez une scène dans le panneau de gauche pour commencer à écrire.',

  words: 'mots',
  word: 'mot',
  scene: 'Scène',
  chapter: 'Chapitre',
  total: 'Total',
  chapters: 'chapitres',
  scenes: 'scènes',

  bold: 'Gras',
  italic: 'Italique',
  underline: 'Souligné',
  heading1: 'Titre 1',
  heading2: 'Titre 2',
  heading3: 'Titre 3',
  bulletList: 'Liste à puces',
  orderedList: 'Liste numérotée',
  blockquote: 'Citation',
  undo: 'Annuler',
  redo: 'Refaire',

  lightMode: 'Mode clair',
  darkMode: 'Mode sombre',

  save: 'Enregistrer',
  cancel: 'Annuler',
  delete: 'Supprimer',
  create: 'Créer',
  back: 'Retour',
  rename: 'Renommer',
  saved: 'Enregistré',

  // Auth
  authSignIn: 'Se connecter',
  authSignUp: 'Créer un compte',
  authSignOut: 'Se déconnecter',
  authEmail: 'Email',
  authPassword: 'Mot de passe',
  authDisplayName: 'Nom d\'affichage',
  authCreateAccount: 'Créer mon compte',
  authLoading: 'Chargement...',
  authForgotPassword: 'Mot de passe oublié ?',
  authResetPassword: 'Réinitialiser le mot de passe',
  authResetSent: 'Un email de réinitialisation a été envoyé. Vérifiez votre boîte de réception.',
  authNewPassword: 'Nouveau mot de passe',
  authNewPasswordConfirm: 'Confirmer le mot de passe',
  authNewPasswordMismatch: 'Les mots de passe ne correspondent pas.',
  authNewPasswordSave: 'Enregistrer le nouveau mot de passe',
  authNewPasswordSuccess: 'Mot de passe mis à jour avec succès !',
  authBackToLogin: 'Retour à la connexion',
  authNoAccount: 'Pas encore de compte ?',
  authHasAccount: 'Déjà un compte ?',
  authConfirmEmail: 'Un email de confirmation vous a été envoyé. Vérifiez votre boîte de réception.',

  // Projects shared
  myProjects: 'Mes projets',
  sharedWithMe: 'Partagés avec moi',
  publicProject: 'Public',
  privateProject: 'Privé',

  // Sharing
  share: 'Partager',
  shareProject: 'Partager le projet',
  shareLink: 'Lien de partage',
  shareLinkCopied: 'Lien copié !',
  sharePublicToggle: 'Projet public',
  sharePublicDesc: 'Tout le monde peut lire ce projet via le lien.',
  collaborators: 'Collaborateurs',
  inviteCollaborator: 'Inviter un collaborateur',
  inviteEmail: 'Email du collaborateur',
  inviteSend: 'Envoyer l\'invitation',
  inviteSent: 'Lien d\'invitation copié ! Partagez-le avec votre collaborateur.',
  inviteAccepted: 'Invitation acceptée ! Le projet a été ajouté à votre liste.',
  inviteError: 'Impossible d\'accepter cette invitation.',
  inviteNotFound: 'Cette invitation est invalide ou a déjà été utilisée.',
  roleEditor: 'Éditeur',
  roleReader: 'Lecteur',
  roleOwner: 'Propriétaire',
  mergeAuthors: 'Fusionner les modifications',
  mergeAuthorsDone: 'Modifications fusionnées !',
  removeCollaborator: 'Retirer',
  readOnly: 'Lecture seule',

  // Characters
  characters: 'Personnages',
  newCharacter: 'Nouveau personnage',
  editCharacter: 'Modifier le personnage',
  deleteCharacter: 'Supprimer le personnage',
  deleteCharacterConfirm: 'Supprimer ce personnage ?',
  characterName: 'Nom',
  characterNamePlaceholder: 'Nom du personnage...',
  characterRole: 'Rôle',
  characterRolePlaceholder: 'Protagoniste, antagoniste...',
  characterDescription: 'Description',
  characterDescriptionPlaceholder: 'Apparence, personnalité...',
  characterNotes: 'Notes',
  characterNotesPlaceholder: 'Notes libres...',
  characterColor: 'Couleur',
  noCharacters: 'Aucun personnage',
  noCharactersHint: 'Créez des fiches personnages pour enrichir votre histoire.',
  linkCharacters: 'Lier des personnages',
  linkedCharacters: 'Personnages liés',

  // Versions
  versionHistory: 'Historique',
  versionRestore: 'Restaurer',
  versionRestoreConfirm: 'Restaurer cette version ? Le contenu actuel sera remplacé.',
  versionPreview: 'Aperçu',
  noVersions: 'Aucune version',
  noVersionsHint: 'Les versions sont créées automatiquement pendant l\'écriture.',
  versionAutoSave: 'Auto-sauvegarde',
  versionManual: 'Sauvegarde manuelle',

  // Fonts
  font: 'Police',
  fontDefault: 'Par défaut',

  // Collaboration
  online: 'En ligne',
  offline: 'Hors ligne',
  collaborating: 'Collaboration',
  connectedUsers: 'Utilisateurs connectés',

  // Errors
  errorGeneric: 'Une erreur est survenue.',
  errorNetwork: 'Erreur de connexion.',
  errorSave: 'Erreur lors de la sauvegarde.',
  migrationDone: 'Vos données locales ont été migrées vers le cloud.',
} as const;
